In [20]:
import pandas as pd
import numpy as np

In [21]:
df = pd.DataFrame({'text':['sanjay raju ajay', "sanjay sanjay raju", "vijay sanjay ajay"],
                   'output':[0,1,1]})
df

text  output
0    sanjay raju ajay       0
1  sanjay sanjay raju       1
2   vijay sanjay ajay       1

In [22]:
df['text']

0      sanjay raju ajay
1    sanjay sanjay raju
2     vijay sanjay ajay
Name: text, dtype: object

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [24]:
bow = cv.fit_transform(df['text'])

In [25]:
print(cv.vocabulary_)

{'sanjay': 2, 'raju': 1, 'ajay': 0, 'vijay': 3}


In [26]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 1 1 0]]
[[0 1 2 0]]
[[1 0 1 1]]


In [27]:
# n gram
cv = CountVectorizer(ngram_range=(2,2))
bow = cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'sanjay raju': 2, 'raju ajay': 0, 'sanjay sanjay': 3, 'vijay sanjay': 4, 'sanjay ajay': 1}


In [28]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0 1 0 0]]
[[0 0 1 1 0]]
[[0 1 0 0 1]]


In [18]:
cv = CountVectorizer(ngram_range=(1,2))
bow = cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'sanjay': 3, 'raju': 1, 'ajay': 0, 'sanjay raju': 5, 'raju ajay': 2, 'sanjay sanjay': 6, 'vijay': 7, 'vijay sanjay': 8, 'sanjay ajay': 4}


In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.61980538, 0.61980538, 0.48133417, 0.        ],
       [0.        , 0.54134281, 0.84080197, 0.        ],
       [0.54783215, 0.        , 0.42544054, 0.72033345]])